Improve Error Handling - exit 1 if runner OS is not supported - exit 1 if clang-tidy installation fail

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -44,8 +44,13 @@ runs:
     - name: Install clang-tidy
       shell: bash
       run: |
-        sudo apt-get update && \
-        sudo apt-get install -y clang-tidy-"${{inputs.version}}"
+        if [ "$RUNNER_OS" = "Linux" ]; then
+          sudo apt-get update && \
+          sudo apt-get install -y clang-tidy-"${{inputs.version}}" || exit 1
+        else
+          printf "Error: OS $RUNNER_OS is not supported\n"
+          exit 1
+        fi
 
     - name: Check code quality
       shell: bash
