Improve Tests (#5)
* Improve Action Test Workflow
- Use matrix build with different OS and versions of clang-tidy
- Use default OS-specific clang version instead of clang-18
- Fix logging issues

* Fix Issues In README.md
- Remove deprecated ubuntu-20.04 from the list of supported platforms

* Add OS Check In Action
- Fail action with exit code 1 if $RUNNER_OS != "Linux"

* Improve Logging

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -41,6 +41,14 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Check runner OS
+      shell: bash
+      run: |
+        if [ "$RUNNER_OS" != "Linux" ]; then
+          printf "Error: OS %s is not supported.\n" "$RUNNER_OS"
+          exit 1
+        fi
+
     - name: Install clang-tidy
       shell: bash
       run: |
